export default [
  {
    id: "51403148-80de-40cb-8000-d8b6b848e184",
    content: "Describe the MVC architecture pattern.",
    topic_name: "Networking",
    answers_submitted_by_user: 1,
    status: "Review & Comment",
  },
  {
    id: "99e90811-bf23-4b6e-a8af-874c391dbbdd",
    content: "Why is normalization important in database design?",
    topic_name: "Web Development",
    answers_submitted_by_user: 2,
    status: "Draft",
  },
  {
    id: "b4dfdf63-18d8-47d3-9936-228470ce9fa0",
    content: "Explain CORS and why it's important for web security.",
    topic_name: "Operating Systems",
    answers_submitted_by_user: 3,
    status: "Draft",
  },
  {
    id: "318cb2b9-2128-4f96-b084-ff87b11f33a8",
    content: "Describe how hashing works in data structures.",
    topic_name: "Java",
    answers_submitted_by_user: 1,
    status: "Review & Comment",
  },
  {
    id: "f5d1398b-1c21-4c52-ae47-9dc6be4c721e",
    content: "Describe the MVC architecture pattern.",
    topic_name: "Cybersecurity",
    answers_submitted_by_user: 2,
    status: "Review & Comment",
  },
  {
    id: "12c56d8a-7606-4f05-9729-254d7f0d46b2",
    content: "How does RESTful API design improve scalability?",
    topic_name: "JavaScript",
    answers_submitted_by_user: 3,
    status: "Review & Comment",
  },
  {
    id: "e69daa63-7f41-4b82-8661-48f1d07f48f4",
    content: "How does the JVM manage memory during program execution?",
    topic_name: "Networking",
    answers_submitted_by_user: 2,
    status: "Draft",
  },
  {
    id: "159569a3-75ec-4d93-8ec3-9631543da198",
    content: "Describe the MVC architecture pattern.",
    topic_name: "Databases",
    answers_submitted_by_user: 2,
    status: "Review & Comment",
  },
  {
    id: "20a1d678-380d-406a-8e95-0e9a42f1d5d4",
    content: "What is multithreading and how does it improve performance?",
    topic_name: "Algorithms",
    answers_submitted_by_user: 3,
    status: "Review & Comment",
  },
  {
    id: "89500514-d025-449f-9551-be63ef9f2b40",
    content: "What's the significance of DNS in internet communication?",
    topic_name: "JavaScript",
    answers_submitted_by_user: 2,
    status: "Review & Comment",
  },
  {
    id: "51e5a025-9cdd-48ce-9519-c3c8073ff955",
    content:
      "Explain the difference between synchronous and asynchronous operations.",
    topic_name: "Algorithms",
    answers_submitted_by_user: 3,
    status: "Review & Comment",
  },
  {
    id: "bd3f2aa1-1734-4ef4-932d-0032c33a6f30",
    content:
      "How does Git handle merge conflicts and how can they be resolved?",
    topic_name: "JavaScript",
    answers_submitted_by_user: 2,
    status: "Review & Comment",
  },
  {
    id: "a56eaecf-f905-4af5-ac78-12bdb0c53cbb",
    content:
      "What are React hooks and how are they different from class components?",
    topic_name: "Data Structures",
    answers_submitted_by_user: 3,
    status: "Draft",
  },
  {
    id: "ab47d409-9908-467c-9984-64936739efc0",
    content: "How is responsive web design implemented using CSS?",
    topic_name: "React",
    answers_submitted_by_user: 3,
    status: "Draft",
  },
  {
    id: "085181e1-05fc-4c11-af7a-d0ce8e743d2d",
    content: "How do indexes improve query performance in databases?",
    topic_name: "Java",
    answers_submitted_by_user: 1,
    status: "Draft",
  },
  {
    id: "f1d15a8c-c8d1-47fa-8424-b263e66e8d51",
    content:
      "How does Git handle merge conflicts and how can they be resolved?",
    topic_name: "Networking",
    answers_submitted_by_user: 2,
    status: "Draft",
  },
  {
    id: "f2c19e83-b9c4-439d-8884-077bd3a307ac",
    content:
      "How does a binary search algorithm work and what is its time complexity?",
    topic_name: "Java",
    answers_submitted_by_user: 3,
    status: "Draft",
  },
  {
    id: "317cc8e9-2c24-4176-864e-b5e9d89de0e8",
    content: "What are the principles of object-oriented programming?",
    topic_name: "Networking",
    answers_submitted_by_user: 1,
    status: "Draft",
  },
  {
    id: "75ba50a9-6d5d-40e1-8a95-233381568ed7",
    content: "Describe the MVC architecture pattern.",
    topic_name: "Cybersecurity",
    answers_submitted_by_user: 3,
    status: "Review & Comment",
  },
  {
    id: "75d65253-041d-4c7d-bdd2-868e84798cb2",
    content: "How is responsive web design implemented using CSS?",
    topic_name: "Java",
    answers_submitted_by_user: 3,
    status: "Review & Comment",
  },
  {
    id: "b66edfe6-ffc2-47a1-ac14-aa1208661bc5",
    content:
      "Describe how Dijkstra\u2019s algorithm finds the shortest path in a graph.",
    topic_name: "Operating Systems",
    answers_submitted_by_user: 1,
    status: "Review & Comment",
  },
  {
    id: "b53ed0b8-2834-4cf7-8de9-6e807e84c182",
    content: "How is responsive web design implemented using CSS?",
    topic_name: "Cybersecurity",
    answers_submitted_by_user: 2,
    status: "Review & Comment",
  },
  {
    id: "ee91002a-bfaa-46a9-ae62-db413b4cce6d",
    content: "What is multithreading and how does it improve performance?",
    topic_name: "Cybersecurity",
    answers_submitted_by_user: 1,
    status: "Review & Comment",
  },
  {
    id: "a8f4324c-4ecc-4e76-9b78-5bf53a5cefa1",
    content: "Describe the MVC architecture pattern.",
    topic_name: "Networking",
    answers_submitted_by_user: 1,
    status: "Review & Comment",
  },
  {
    id: "469efd67-8bf5-4604-81cf-c50a6243a76e",
    content: "How do operating systems manage process scheduling?",
    topic_name: "React",
    answers_submitted_by_user: 2,
    status: "Review & Comment",
  },
  {
    id: "3ef10336-b458-48e4-9a7f-c7724ff35827",
    content: "How is responsive web design implemented using CSS?",
    topic_name: "Operating Systems",
    answers_submitted_by_user: 2,
    status: "Draft",
  },
  {
    id: "096dc8dd-40da-4197-84a7-653685d75571",
    content: "How is responsive web design implemented using CSS?",
    topic_name: "Cybersecurity",
    answers_submitted_by_user: 2,
    status: "Draft",
  },
  {
    id: "001564c2-041a-486d-a807-460adfa9795f",
    content: "Describe how hashing works in data structures.",
    topic_name: "React",
    answers_submitted_by_user: 2,
    status: "Draft",
  },
  {
    id: "af1f965f-310b-4eaf-8186-05496fc55db3",
    content: "How does the JVM manage memory during program execution?",
    topic_name: "React",
    answers_submitted_by_user: 3,
    status: "Draft",
  },
  {
    id: "e0eba3e2-1d71-4f2c-a178-a29856d1b670",
    content: "How do operating systems manage process scheduling?",
    topic_name: "Networking",
    answers_submitted_by_user: 2,
    status: "Review & Comment",
  },
  {
    id: "3faa2cd1-78a2-4a51-9ca6-e4bc2c19b9c4",
    content: "How does recursion differ from iteration in programming?",
    topic_name: "Data Structures",
    answers_submitted_by_user: 3,
    status: "Review & Comment",
  },
  {
    id: "57741ecf-dd29-4697-bea7-80620bd12735",
    content: "How does RESTful API design improve scalability?",
    topic_name: "Algorithms",
    answers_submitted_by_user: 3,
    status: "Draft",
  },
  {
    id: "8c9d1867-8ff7-41cd-8623-0d71d7224da6",
    content: "Describe the working of garbage collection in Java.",
    topic_name: "Algorithms",
    answers_submitted_by_user: 2,
    status: "Draft",
  },
  {
    id: "ece74de2-322d-423c-b570-f1946ef8e53d",
    content:
      "How does a binary search algorithm work and what is its time complexity?",
    topic_name: "Algorithms",
    answers_submitted_by_user: 2,
    status: "Draft",
  },
  {
    id: "5d2f97f5-9050-43c4-b218-8ec704c0f20d",
    content:
      "Explain the difference between synchronous and asynchronous operations.",
    topic_name: "Data Structures",
    answers_submitted_by_user: 1,
    status: "Review & Comment",
  },
  {
    id: "9bab21b9-6242-473a-94c0-699c39ab9efa",
    content: "What are the advantages of cloud computing for businesses?",
    topic_name: "Web Development",
    answers_submitted_by_user: 1,
    status: "Draft",
  },
  {
    id: "b344e70a-a9a7-42b2-9f1b-f38de53a9ad9",
    content: "What are the advantages of cloud computing for businesses?",
    topic_name: "Databases",
    answers_submitted_by_user: 1,
    status: "Review & Comment",
  },
  {
    id: "3f35d7ad-9f03-4e41-83f2-38e3a9033da7",
    content:
      "Explain the concept of closures in JavaScript with a simple example.",
    topic_name: "JavaScript",
    answers_submitted_by_user: 1,
    status: "Review & Comment",
  },
  {
    id: "1a43cdc4-be15-4d20-a21d-8d4614295ea8",
    content: "What is multithreading and how does it improve performance?",
    topic_name: "Web Development",
    answers_submitted_by_user: 2,
    status: "Draft",
  },
  {
    id: "c82fb770-7935-4f47-8cfa-2eabd67b54d2",
    content: "Why is normalization important in database design?",
    topic_name: "Operating Systems",
    answers_submitted_by_user: 2,
    status: "Review & Comment",
  },
  {
    id: "799a54de-05c7-4c78-b141-296d55e3fe6b",
    content:
      "How does a binary search algorithm work and what is its time complexity?",
    topic_name: "Databases",
    answers_submitted_by_user: 2,
    status: "Review & Comment",
  },
  {
    id: "0bc4db47-1669-4ee8-8fb6-9f878b72eb43",
    content:
      "Describe how Dijkstra\u2019s algorithm finds the shortest path in a graph.",
    topic_name: "Operating Systems",
    answers_submitted_by_user: 3,
    status: "Draft",
  },
  {
    id: "643608ac-3ddd-4205-835e-c780ca3f10d8",
    content: "How do operating systems manage process scheduling?",
    topic_name: "Operating Systems",
    answers_submitted_by_user: 2,
    status: "Review & Comment",
  },
  {
    id: "a2ca7c61-50d3-4b7b-8a01-51ccefadbc06",
    content: "Explain how blockchain ensures data integrity.",
    topic_name: "JavaScript",
    answers_submitted_by_user: 3,
    status: "Draft",
  },
  {
    id: "873c72d0-2901-48a4-9668-ee98951e84d7",
    content: "What is event bubbling in JavaScript?",
    topic_name: "Networking",
    answers_submitted_by_user: 1,
    status: "Review & Comment",
  },
  {
    id: "2e320cae-856a-4d9d-8438-7540c8da096c",
    content: "Why is normalization important in database design?",
    topic_name: "React",
    answers_submitted_by_user: 3,
    status: "Review & Comment",
  },
  {
    id: "a058e124-bbc8-41a8-bb71-aec1e1936250",
    content: "How does the JVM manage memory during program execution?",
    topic_name: "Java",
    answers_submitted_by_user: 2,
    status: "Draft",
  },
  {
    id: "34238eaa-c67a-47e4-ab80-6f81e8ab1a13",
    content: "What is event bubbling in JavaScript?",
    topic_name: "Databases",
    answers_submitted_by_user: 1,
    status: "Review & Comment",
  },
  {
    id: "921b5b16-0de0-409a-95a9-acc2bc0cc155",
    content: "How is responsive web design implemented using CSS?",
    topic_name: "Java",
    answers_submitted_by_user: 3,
    status: "Review & Comment",
  },
  {
    id: "5a0b4e7c-ee9d-47cd-a555-e18eb0e32794",
    content:
      "How does Git handle merge conflicts and how can they be resolved?",
    topic_name: "Java",
    answers_submitted_by_user: 3,
    status: "Draft",
  },
  {
    id: "3b6be496-58c6-4458-b23e-3f937f298578",
    content: "What's the significance of DNS in internet communication?",
    topic_name: "Cybersecurity",
    answers_submitted_by_user: 3,
    status: "Draft",
  },
  {
    id: "ec554013-0964-4986-bc2e-c469690e94b6",
    content:
      "Explain the difference between synchronous and asynchronous operations.",
    topic_name: "Data Structures",
    answers_submitted_by_user: 1,
    status: "Review & Comment",
  },
  {
    id: "ab51950a-58e6-41f0-834d-2ed7b3acf33b",
    content: "Describe the working of garbage collection in Java.",
    topic_name: "Operating Systems",
    answers_submitted_by_user: 3,
    status: "Review & Comment",
  },
  {
    id: "41a12ee0-faee-46b5-bd12-9ea595d293df",
    content: "How do operating systems manage process scheduling?",
    topic_name: "Algorithms",
    answers_submitted_by_user: 2,
    status: "Review & Comment",
  },
  {
    id: "cf47f76b-abc4-4a26-9745-bc17cd4df67d",
    content: "What are the major differences between TCP and UDP protocols?",
    topic_name: "Web Development",
    answers_submitted_by_user: 1,
    status: "Draft",
  },
  {
    id: "88683009-155b-4899-8268-c5562065a98e",
    content:
      "Describe how Dijkstra\u2019s algorithm finds the shortest path in a graph.",
    topic_name: "Web Development",
    answers_submitted_by_user: 2,
    status: "Review & Comment",
  },
  {
    id: "14bed1ef-750d-41ba-81da-603baeffa7bd",
    content: "How does recursion differ from iteration in programming?",
    topic_name: "Algorithms",
    answers_submitted_by_user: 1,
    status: "Review & Comment",
  },
  {
    id: "4edd618a-e4bb-4085-9901-cbfa53e31ff5",
    content: "Describe the working of garbage collection in Java.",
    topic_name: "Operating Systems",
    answers_submitted_by_user: 2,
    status: "Review & Comment",
  },
  {
    id: "22cd28cb-6a05-4484-9f1c-1ef588d62bf3",
    content: "How does the JVM manage memory during program execution?",
    topic_name: "JavaScript",
    answers_submitted_by_user: 1,
    status: "Review & Comment",
  },
  {
    id: "9f21ebd4-b296-4e37-923d-fd5f867149e7",
    content:
      "Explain the difference between synchronous and asynchronous operations.",
    topic_name: "Cybersecurity",
    answers_submitted_by_user: 2,
    status: "Draft",
  },
  {
    id: "6493b238-2536-4c14-b481-b3dfe0e8e574",
    content: "Describe the MVC architecture pattern.",
    topic_name: "Web Development",
    answers_submitted_by_user: 3,
    status: "Draft",
  },
  {
    id: "7ba4d0e1-ec74-45e3-91d6-bb83b82d6660",
    content: "What are the advantages of cloud computing for businesses?",
    topic_name: "JavaScript",
    answers_submitted_by_user: 3,
    status: "Draft",
  },
  {
    id: "3aba731e-da68-4a6a-9e59-b81d35dd8b26",
    content: "What are the advantages of cloud computing for businesses?",
    topic_name: "Data Structures",
    answers_submitted_by_user: 2,
    status: "Review & Comment",
  },
  {
    id: "6203a6f1-4684-46f2-8040-89d86b714000",
    content: "What is multithreading and how does it improve performance?",
    topic_name: "Web Development",
    answers_submitted_by_user: 2,
    status: "Review & Comment",
  },
  {
    id: "135263ff-58a6-4c13-8d4d-a359b86bffc5",
    content: "What are the major differences between TCP and UDP protocols?",
    topic_name: "Data Structures",
    answers_submitted_by_user: 3,
    status: "Review & Comment",
  },
  {
    id: "57c270c5-2fd2-4a20-8967-e138bf9c24c3",
    content:
      "Explain the difference between synchronous and asynchronous operations.",
    topic_name: "React",
    answers_submitted_by_user: 2,
    status: "Review & Comment",
  },
  {
    id: "a3093a3e-ed32-4c13-8a93-a74f5e2831b1",
    content: "Describe the working of garbage collection in Java.",
    topic_name: "Web Development",
    answers_submitted_by_user: 3,
    status: "Review & Comment",
  },
  {
    id: "f3b0de85-6cda-4f28-93e8-9f7e42974bdd",
    content: "How do operating systems manage process scheduling?",
    topic_name: "Networking",
    answers_submitted_by_user: 2,
    status: "Draft",
  },
  {
    id: "1f49a282-c471-46ec-b125-bb0b2100ace2",
    content: "Describe the working of garbage collection in Java.",
    topic_name: "Web Development",
    answers_submitted_by_user: 1,
    status: "Review & Comment",
  },
  {
    id: "a4b77451-ac6c-443e-8b66-e967b48bf5e6",
    content: "Explain how blockchain ensures data integrity.",
    topic_name: "Networking",
    answers_submitted_by_user: 2,
    status: "Review & Comment",
  },
];
